package com.cisco.sonic.converter.output;

import com.cisco.sonic.converter.model.SonicConfig;
import java.util.*;

/**
 * Generates SONiC CLI commands from SonicConfig object
 * Produces executable shell script with SONiC CLI commands
 */
public class SonicCliGenerator {
    
    /**
     * Generate SONiC CLI commands as a string
     */
    public String generateCommands(SonicConfig config) {
        StringBuilder sb = new StringBuilder();
        
        // Header
        sb.append("#!/bin/bash\n");
        sb.append("# SONiC Configuration Script\n");
        sb.append("# Generated by Cisco to SONiC Configuration Converter\n");
        sb.append("#\n");
        sb.append("# This script contains SONiC CLI commands to configure the device.\n");
        sb.append("# Run this script on a SONiC device with appropriate permissions.\n");
        sb.append("#\n\n");
        
        sb.append("echo \"Starting SONiC configuration...\"\n\n");
        
        // Device metadata (hostname)
        generateHostnameCommands(config, sb);
        
        // VLANs
        generateVlanCommands(config, sb);

        // Port-Channels
        generatePortChannelCommands(config, sb);

        // Interfaces
        generateInterfaceCommands(config, sb);

        // VLAN interfaces
        generateVlanInterfaceCommands(config, sb);

        // VLAN members
        generateVlanMemberCommands(config, sb);

        // Static routes
        generateStaticRouteCommands(config, sb);
        
        // ACLs
        generateAclCommands(config, sb);
        
        // Footer
        sb.append("\necho \"Configuration completed!\"\n");
        sb.append("echo \"Please verify the configuration with 'show' commands.\"\n");
        
        return sb.toString();
    }
    
    private void generateHostnameCommands(SonicConfig config, StringBuilder sb) {
        Map<String, Object> metadata = config.getDeviceMetadata();
        if (metadata.containsKey("localhost")) {
            @SuppressWarnings("unchecked")
            Map<String, Object> localhost = (Map<String, Object>) metadata.get("localhost");
            
            if (localhost.containsKey("hostname")) {
                String hostname = (String) localhost.get("hostname");
                sb.append("# Configure hostname\n");
                sb.append("echo \"Setting hostname to ").append(hostname).append("...\"\n");
                sb.append("sudo config hostname ").append(hostname).append("\n\n");
            }
        }
    }
    
    private void generateVlanCommands(SonicConfig config, StringBuilder sb) {
        Map<String, Map<String, Object>> vlans = config.getVlans();
        if (!vlans.isEmpty()) {
            sb.append("# Configure VLANs\n");
            sb.append("echo \"Configuring VLANs...\"\n");
            
            for (Map.Entry<String, Map<String, Object>> entry : vlans.entrySet()) {
                String vlanName = entry.getKey();
                Map<String, Object> vlanConfig = entry.getValue();
                
                if (vlanConfig.containsKey("vlanid")) {
                    String vlanId = (String) vlanConfig.get("vlanid");
                    sb.append("sudo config vlan add ").append(vlanId);
                    
                    // Add description as comment if available
                    if (vlanConfig.containsKey("description")) {
                        sb.append("  # ").append(vlanConfig.get("description"));
                    }
                    sb.append("\n");
                }
            }
            sb.append("\n");
        }
    }

    private void generatePortChannelCommands(SonicConfig config, StringBuilder sb) {
        Map<String, Map<String, Object>> portChannels = config.getPortChannels();
        Map<String, Map<String, Object>> portChannelMembers = config.getPortChannelMembers();

        if (!portChannels.isEmpty()) {
            sb.append("# Configure Port-Channels (LAGs)\n");
            sb.append("echo \"Configuring Port-Channels...\"\n");

            // Create Port-Channels
            for (Map.Entry<String, Map<String, Object>> entry : portChannels.entrySet()) {
                String portChannelName = entry.getKey();
                Map<String, Object> portChannelConfig = entry.getValue();

                // Add Port-Channel
                sb.append("sudo config portchannel add ").append(portChannelName).append("\n");

                // Set min_links if specified
                if (portChannelConfig.containsKey("min_links")) {
                    sb.append("# Min links: ").append(portChannelConfig.get("min_links")).append("\n");
                }
            }
            sb.append("\n");

            // Add Port-Channel members
            if (!portChannelMembers.isEmpty()) {
                sb.append("# Add Port-Channel members\n");
                for (Map.Entry<String, Map<String, Object>> entry : portChannelMembers.entrySet()) {
                    String memberKey = entry.getKey();

                    // Format: "PortChannel1|Ethernet1"
                    String[] parts = memberKey.split("\\|");
                    if (parts.length == 2) {
                        String portChannelName = parts[0];
                        String memberPort = parts[1];

                        sb.append("sudo config portchannel member add ").append(portChannelName);
                        sb.append(" ").append(memberPort).append("\n");
                    }
                }
                sb.append("\n");
            }
        }
    }

    private void generateInterfaceCommands(SonicConfig config, StringBuilder sb) {
        Map<String, Map<String, Object>> ports = config.getPorts();
        Map<String, Map<String, Object>> interfaces = config.getInterfaces();
        
        if (!ports.isEmpty() || !interfaces.isEmpty()) {
            sb.append("# Configure interfaces\n");
            sb.append("echo \"Configuring interfaces...\"\n");
            
            // Process ports (admin status, MTU, speed, description)
            for (Map.Entry<String, Map<String, Object>> entry : ports.entrySet()) {
                String portName = entry.getKey();
                Map<String, Object> portConfig = entry.getValue();
                
                // Skip VLAN interfaces (they're handled separately)
                if (portName.startsWith("Vlan")) {
                    continue;
                }
                
                // Add description as comment
                if (portConfig.containsKey("description")) {
                    sb.append("# ").append(portName).append(": ").append(portConfig.get("description")).append("\n");
                }
                
                // Admin status
                if (portConfig.containsKey("admin_status")) {
                    String adminStatus = (String) portConfig.get("admin_status");
                    sb.append("sudo config interface ").append(adminStatus.equals("up") ? "startup" : "shutdown");
                    sb.append(" ").append(portName).append("\n");
                }
                
                // MTU
                if (portConfig.containsKey("mtu")) {
                    sb.append("sudo config interface mtu ").append(portName);
                    sb.append(" ").append(portConfig.get("mtu")).append("\n");
                }
                
                // Speed
                if (portConfig.containsKey("speed")) {
                    sb.append("sudo config interface speed ").append(portName);
                    sb.append(" ").append(portConfig.get("speed")).append("\n");
                }
            }

            // Process IP addresses on interfaces
            for (Map.Entry<String, Map<String, Object>> entry : interfaces.entrySet()) {
                String interfaceKey = entry.getKey();
                // Format: "Ethernet1|10.0.1.1/30"
                String[] parts = interfaceKey.split("\\|");
                if (parts.length == 2) {
                    String portName = parts[0];
                    String ipAddress = parts[1];

                    // Skip VLAN interfaces (handled separately)
                    if (!portName.startsWith("Vlan")) {
                        sb.append("sudo config interface ip add ").append(portName);
                        sb.append(" ").append(ipAddress).append("\n");
                    }
                }
            }
            sb.append("\n");
        }
    }

    private void generateVlanInterfaceCommands(SonicConfig config, StringBuilder sb) {
        Map<String, Map<String, Object>> vlanInterfaces = config.getVlanInterfaces();
        Map<String, Map<String, Object>> ports = config.getPorts();

        if (!vlanInterfaces.isEmpty()) {
            sb.append("# Configure VLAN interfaces (SVIs)\n");
            sb.append("echo \"Configuring VLAN interfaces...\"\n");

            for (Map.Entry<String, Map<String, Object>> entry : vlanInterfaces.entrySet()) {
                String interfaceKey = entry.getKey();
                // Format: "Vlan10|192.168.10.1/24"
                String[] parts = interfaceKey.split("\\|");
                if (parts.length == 2) {
                    String vlanName = parts[0];
                    String ipAddress = parts[1];

                    sb.append("sudo config interface ip add ").append(vlanName);
                    sb.append(" ").append(ipAddress).append("\n");

                    // Set admin status if available
                    if (ports.containsKey(vlanName)) {
                        Map<String, Object> portConfig = ports.get(vlanName);
                        if (portConfig.containsKey("admin_status")) {
                            String adminStatus = (String) portConfig.get("admin_status");
                            sb.append("sudo config interface ").append(adminStatus.equals("up") ? "startup" : "shutdown");
                            sb.append(" ").append(vlanName).append("\n");
                        }
                    }
                }
            }
            sb.append("\n");
        }
    }

    private void generateVlanMemberCommands(SonicConfig config, StringBuilder sb) {
        Map<String, Map<String, Object>> vlanMembers = config.getVlanMembers();

        if (!vlanMembers.isEmpty()) {
            sb.append("# Configure VLAN memberships\n");
            sb.append("echo \"Configuring VLAN memberships...\"\n");

            for (Map.Entry<String, Map<String, Object>> entry : vlanMembers.entrySet()) {
                String memberKey = entry.getKey();
                Map<String, Object> memberConfig = entry.getValue();

                // Format: "Vlan20|Ethernet2"
                String[] parts = memberKey.split("\\|");
                if (parts.length == 2) {
                    String vlanName = parts[0];
                    String portName = parts[1];

                    // Extract VLAN ID from name (e.g., "Vlan20" -> "20")
                    String vlanId = vlanName.substring(4);

                    sb.append("sudo config vlan member add ");

                    // Add tagging mode flag
                    if (memberConfig.containsKey("tagging_mode")) {
                        String taggingMode = (String) memberConfig.get("tagging_mode");
                        if (taggingMode.equals("tagged")) {
                            sb.append("-u ");  // -u for tagged (trunk)
                        }
                    }

                    sb.append(vlanId).append(" ").append(portName).append("\n");
                }
            }
            sb.append("\n");
        }
    }

    private void generateStaticRouteCommands(SonicConfig config, StringBuilder sb) {
        Map<String, Map<String, Object>> staticRoutes = config.getStaticRoutes();

        if (!staticRoutes.isEmpty()) {
            sb.append("# Configure static routes\n");
            sb.append("echo \"Configuring static routes...\"\n");

            for (Map.Entry<String, Map<String, Object>> entry : staticRoutes.entrySet()) {
                String routeKey = entry.getKey();
                Map<String, Object> routeConfig = entry.getValue();

                // Format: "0.0.0.0/0|0.0.0.0/0|10.0.1.2"
                String[] parts = routeKey.split("\\|");
                if (parts.length >= 3) {
                    String prefix = parts[0];
                    String nexthop = parts[2];

                    sb.append("sudo config route add prefix ").append(prefix);
                    sb.append(" nexthop ").append(nexthop);

                    // Add interface if specified
                    if (routeConfig.containsKey("ifname")) {
                        String ifname = (String) routeConfig.get("ifname");
                        if (ifname != null && !ifname.isEmpty()) {
                            sb.append(" dev ").append(ifname);
                        }
                    }

                    sb.append("\n");
                }
            }
            sb.append("\n");
        }
    }

    private void generateAclCommands(SonicConfig config, StringBuilder sb) {
        Map<String, Map<String, Object>> aclTables = config.getAclTables();
        Map<String, Map<String, Object>> aclRules = config.getAclRules();

        if (!aclTables.isEmpty() || !aclRules.isEmpty()) {
            sb.append("# Configure ACLs\n");
            sb.append("echo \"Configuring ACLs...\"\n");
            sb.append("# Note: ACL configuration via CLI may be limited.\n");
            sb.append("# For complex ACLs, consider using JSON configuration directly.\n");

            // ACL tables
            for (Map.Entry<String, Map<String, Object>> entry : aclTables.entrySet()) {
                String tableName = entry.getKey();
                Map<String, Object> tableConfig = entry.getValue();

                sb.append("# ACL Table: ").append(tableName);
                if (tableConfig.containsKey("type")) {
                    sb.append(" (Type: ").append(tableConfig.get("type")).append(")");
                }
                sb.append("\n");
                sb.append("# ACL rules should be configured via acl-loader or JSON config\n");
            }

            sb.append("\n");
        }
    }
}


